// Generated by CoffeeScript 1.4.0
(function() {
  var BoardSchema, ObjectId, errors, mongoose, pluginTimestamp, _;

  _ = require('underscore');

  mongoose = require('mongoose');

  pluginTimestamp = require("mongoose-plugins-timestamp");

  errors = require('some-errors');

  ObjectId = mongoose.Schema.ObjectId;

  module.exports = BoardSchema = new mongoose.Schema({
    name: {
      type: String,
      required: true,
      unique: true
    },
    states: {
      type: [String],
      "default": function() {
        return [];
      }
    },
    captions: {
      type: [String],
      "default": function() {
        return [];
      }
    }
  }, {
    strict: true
  });

  BoardSchema.plugin(pluginTimestamp.timestamps);

  /*
  RoleSchema.pre 'save', (next) ->
    @name = (@name || '').toLowerCase()
  
    next()
  */


}).call(this);
