// Generated by CoffeeScript 1.4.0
(function() {
  var ObjectId, RoleSchema, errors, mongoose, pluginTimestamp, _;

  _ = require('underscore');

  mongoose = require('mongoose');

  pluginTimestamp = require("mongoose-plugins-timestamp");

  errors = require('some-errors');

  ObjectId = mongoose.Schema.ObjectId;

  module.exports = RoleSchema = new mongoose.Schema({
    name: {
      type: String,
      required: true,
      unique: true
    }
  }, {
    strict: true
  });

  RoleSchema.plugin(pluginTimestamp.timestamps);

  RoleSchema.pre('save', function(next) {
    this.name = (this.name || '').toLowerCase();
    return next();
  });

}).call(this);
