// Generated by CoffeeScript 1.4.0
(function() {
  var Client, Identity, request, xmlParser, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  request = require('request');

  _ = require('underscore');

  xmlParser = require("libxmljs-easy");

  /*
  Sample requests
  curl -X POST -d '' -H 'Content-Type: application/xml' -H 'Accept: application/xml' http://ec2-54-251-77-10/bonita-server-rest/API/identityAPI/getAllRoles
  
  admin:bpm
  */


  Identity = require('./identity');

  module.exports = Client = (function() {

    function Client(endpoint, username, password, options) {
      this.endpoint = endpoint;
      this.username = username;
      this.password = password;
      this.options = options != null ? options : {};
      this.get = __bind(this.get, this);

      this["delete"] = __bind(this["delete"], this);

      this.put = __bind(this.put, this);

      this.patch = __bind(this.patch, this);

      this.post = __bind(this.post, this);

      this._reqWithData = __bind(this._reqWithData, this);

      this._getAuth = __bind(this._getAuth, this);

      this._handleResult = __bind(this._handleResult, this);

      this._cleanEndpoint = __bind(this._cleanEndpoint, this);

      this.endpoint = this._cleanEndpoint(this.endpoint);
      if (!(this.endpoint && this.endpoint.length > 0)) {
        throw new Error("Endpoint required");
      }
      if (!(this.username && this.username.length > 0)) {
        throw new Error("Username required");
      }
      if (!(this.password && this.password.length > 0)) {
        throw new Error("Password required");
      }
      _.defaults(this.options, {
        maxCacheItems: 1000,
        headers: {}
      });
      this.cache = {};
      this.identity = new Identity(this);
    }

    Client.prototype._cleanEndpoint = function(endpoint) {
      if (!endpoint) {
        return null;
      }
      return endpoint.replace(/\/+$/, "");
    };

    Client.prototype._handleResult = function(res, bodyBeforeXml, callback) {
      var body;
      if (res.statusCode === 401 || res.statusCode === 403) {
        return callback(new errors.AccessDenied(""));
      }
      body = null;
      if (bodyBeforeXml && bodyBeforeXml.length > 0) {
        try {
          body = xmlParser.parse(bodyBeforeXml);
        } catch (e) {
          return callback(new Error("Invalid Body Content"), bodyBeforeXml, res.statusCode);
        }
      }
      if (!(res.statusCode >= 200 && res.statusCode < 300)) {
        return callback(new Error(body ? body.message : "Request failed."));
      }
      return callback(null, body, res.statusCode);
    };

    Client.prototype._getAuth = function() {
      return new Buffer("" + this.username + ":" + password).toString('base64');
    };

    Client.prototype._reqWithData = function(method, path, data, opt, callback) {
      var headers,
        _this = this;
      headers = {
        'Content-Type': 'application/xml',
        'Accept': 'application/xml',
        'authorization': "Basic " + (this._getAuth())
      };
      _.extend(headers, this.options.headers);
      return request({
        uri: "" + this.endpoint + path,
        headers: headers,
        body: data ? JSON.stringify(data) : null,
        method: method,
        timeout: 2000
      }, function(err, res, body) {
        if (err) {
          err.status = res.statusCode;
          return callback(err);
        }
        return _this._handleResult(res, body, callback);
      });
    };

    Client.prototype.post = function(path, data, opt, callback) {
      if (opt == null) {
        opt = {};
      }
      return this._reqWithData("POST", path, data, options, callback);
    };

    Client.prototype.patch = function(path, data, opt, callback) {
      if (opt == null) {
        opt = {};
      }
      return this._reqWithData("PATCH", path, data, options, callback);
    };

    Client.prototype.put = function(path, data, opt, callback) {
      if (opt == null) {
        opt = {};
      }
      return this._reqWithData("PUT", path, data, options, callback);
    };

    Client.prototype["delete"] = function(path, opt, callback) {
      var headers,
        _this = this;
      if (opt == null) {
        opt = {};
      }
      headers = {
        'Accept': 'application/xml',
        'authorization': "Basic " + (this._getAuth())
      };
      _.extend(headers, this.options.headers);
      return request({
        uri: "" + this.endpoint + path,
        headers: headers,
        method: 'DELETE'
      }, function(err, res, body) {
        if (err) {
          err.status = res.statusCode;
          return callback(err);
        }
        return _this._handleResult(res, body, callback);
      });
    };

    Client.prototype.get = function(path, opt, callback) {
      var headers,
        _this = this;
      if (opt == null) {
        opt = {};
      }
      if (!callback && _.isFunction(opt)) {
        callback = opt;
        opt = {};
      }
      headers = {
        'Accept': 'application/xml',
        'authorization': "Basic " + (this._getAuth())
      };
      _.extend(headers, this.options.headers);
      return request({
        uri: "" + this.endpoint + path,
        headers: headers,
        method: 'GET'
      }, function(err, res, body) {
        if (err) {
          err.status = res.statusCode;
          return callback(err);
        }
        return _this._handleResult(res, body, callback);
      });
    };

    return Client;

  })();

}).call(this);
