// Generated by CoffeeScript 1.4.0
(function() {
  var Client, Identity, QueryDefinition, QueryRuntime, qs, request, xmlParser, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  request = require('request');

  _ = require('underscore');

  xmlParser = require("libxmljs-easy");

  qs = require('querystring');

  /*
  Sample requests
  curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/identityAPI/getAllUsers
  
  admin:bpm
  
  
  curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/queryDefinitionAPI/getProcesses
  
  Retrieve board data for that process
  curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/queryRuntimeAPI/getProcessInstances/QA_Data_Entry--1.2
  
  Retrieve the uuid for the active process with that name
  curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/queryDefinitionAPI/getLastProcess/QA_Data_Entry
  */


  Identity = require('./identity');

  QueryRuntime = require('./query-runtime');

  QueryDefinition = require('./query-definition');

  module.exports = Client = (function() {

    function Client(endpoint, username, password, options) {
      this.endpoint = endpoint;
      this.username = username;
      this.password = password;
      this.options = options != null ? options : {};
      this.post = __bind(this.post, this);

      this._reqWithData = __bind(this._reqWithData, this);

      this._getAuth = __bind(this._getAuth, this);

      this._handleResult = __bind(this._handleResult, this);

      this._cleanEndpoint = __bind(this._cleanEndpoint, this);

      this.endpoint = this._cleanEndpoint(this.endpoint);
      if (!(this.endpoint && this.endpoint.length > 0)) {
        throw new Error("Endpoint required");
      }
      if (!(this.username && this.username.length > 0)) {
        throw new Error("Username required");
      }
      if (!(this.password && this.password.length > 0)) {
        throw new Error("Password required");
      }
      this.options = {};
      _.defaults(this.options, {
        maxCacheItems: 1000,
        headers: {}
      });
      this.cache = {};
      this.identity = new Identity(this);
      this.queryRuntime = new QueryRuntime(this);
      this.queryDefinition = new QueryDefinition(this);
    }

    Client.prototype._cleanEndpoint = function(endpoint) {
      if (!endpoint) {
        return null;
      }
      return endpoint.replace(/\/+$/, "");
    };

    Client.prototype._handleResult = function(res, bodyBeforeXml, callback) {
      var body;
      console.log("GOT THIS: " + bodyBeforeXml);
      if (res.statusCode === 401 || res.statusCode === 403) {
        return callback(new errors.AccessDenied(""));
      }
      body = null;
      if (bodyBeforeXml && bodyBeforeXml.length > 0) {
        try {
          body = xmlParser.parse(bodyBeforeXml);
        } catch (e) {
          return callback(new Error("Invalid Body Content"), bodyBeforeXml, res.statusCode);
        }
      }
      if (!(res.statusCode >= 200 && res.statusCode < 300)) {
        return callback(new Error(body ? body.message : "Request failed."));
      }
      return callback(null, body, res.statusCode);
    };

    Client.prototype._getAuth = function() {
      return new Buffer("" + this.username + ":" + this.password).toString('base64');
    };

    Client.prototype._reqWithData = function(method, path, data, actAsUser, opt, callback) {
      var headers,
        _this = this;
      if (data == null) {
        data = {};
      }
      headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Accept': 'application/xml',
        'authorization': "Basic " + (this._getAuth())
      };
      _.extend(headers, this.options.headers);
      if (actAsUser) {
        data.user = actAsUser;
      }
      return request({
        uri: "" + this.endpoint + path,
        headers: headers,
        body: data ? qs.stringify(data) : null,
        method: method,
        timeout: 2000
      }, function(err, res, body) {
        if (err) {
          err.status = res.statusCode;
          return callback(err);
        }
        return _this._handleResult(res, body, callback);
      });
    };

    Client.prototype.post = function(path, data, opt, callback) {
      if (opt == null) {
        opt = {};
      }
      return this._reqWithData("POST", path, data, opt, callback);
    };

    /*
      patch: (path, data, opt = {}, callback) =>
        @_reqWithData "PATCH", path, data, opt, callback
    
      put: (path, data, opt = {}, callback) =>
        @_reqWithData "PUT", path, data, opt, callback
    
    
    
      delete: (path,actAsUser, opt = {}, callback) =>
        headers =
          'Accept' : 'application/xml'
          'authorization' : "Basic #{@_getAuth()}"
    
        _.extend headers, @options.headers
    
        request
          uri: "#{@endpoint}#{path}"
          headers: headers
          method: 'DELETE'
         , (err, res, body) =>
            if err
              err.status = res.statusCode
              return callback(err)
    
            @_handleResult res, body, callback
    
      get: (path,actAsUser, opt = {}, callback) =>
        if !callback && _.isFunction opt
          callback = opt
          opt = {}
    
        headers =
          'Accept' : 'application/xml'
          'authorization' : "Basic #{@_getAuth()}"
    
        _.extend headers, @options.headers
    
        request
          uri: "#{@endpoint}#{path}"
          headers: headers
          method: 'GET'
         , (err, res, body) =>
           if err
             err.status = res.statusCode
             return callback(err)
           @_handleResult res, body, callback
    */


    return Client;

  })();

}).call(this);
