// Generated by CoffeeScript 1.4.0

/*
Handles the identity API in bonita
*/


(function() {
  var Identity,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Identity = (function() {

    function Identity(client) {
      this.client = client;
      this.getAllUsers = __bind(this.getAllUsers, this);

      if (!this.client) {
        throw new Error("client parameter is required");
      }
    }

    Identity.prototype.getAllUsers = function(opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/identityAPI/getAllUsers", opts, cb);
    };

    return Identity;

  })();

}).call(this);
