// Generated by CoffeeScript 1.4.0

/*
Handles the identity API in bonita
*/


(function() {
  var Identity,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Identity = (function() {

    function Identity(client) {
      this.client = client;
      this.addRoleToUser = __bind(this.addRoleToUser, this);

      this.addUser = __bind(this.addUser, this);

      this.getAllUsers = __bind(this.getAllUsers, this);

      if (!this.client) {
        throw new Error("client parameter is required");
      }
    }

    Identity.prototype.getAllUsers = function(actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/identityAPI/getAllUsers", actAsUser, {}, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:admin&username=martin&password=1234' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/identityAPI/addUser
      RETURNS:
      <User>
        <dbid>624</dbid>
        <uuid>56ad8150-20af-40dd-934f-6169fca5e7e3</uuid>
        <password>7110eda4d09e62aa5e4a390b0a572acd2c220</password>
        <username>martin</username>
      </User>
    */


    Identity.prototype.addUser = function(username, password, actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/identityAPI/addUser", actAsUser, {
        username: username,
        password: password
      }, {}, cb);
    };

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/identityAPI/addRoleToUser/admin/martin
    */


    Identity.prototype.addRoleToUser = function(username, role, actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/identityAPI/addRoleToUser/" + role + "/" + username, actAsUser, {}, {}, cb);
    };

    return Identity;

  })();

}).call(this);
