// Generated by CoffeeScript 1.4.0

/*
Handles the identity API in bonita
*/


(function() {
  var QueryRuntime,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = QueryRuntime = (function() {

    function QueryRuntime(client) {
      this.client = client;
      this.getProcessInstances = __bind(this.getProcessInstances, this);

      if (!this.client) {
        throw new Error("client parameter is required");
      }
    }

    QueryRuntime.prototype.getProcessInstances = function(processUUID, actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/queryRuntimeAPI/getProcessInstances/" + processUUID, actAsUser, opts, cb);
    };

    return QueryRuntime;

  })();

}).call(this);
