// Generated by CoffeeScript 1.4.0

/*
Handles the identity API in bonita
*/


(function() {
  var Runtime,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Runtime = (function() {

    function Runtime(client) {
      this.client = client;
      this.startActivity = __bind(this.startActivity, this);

      this.startTask = __bind(this.startTask, this);

      this.assignTask = __bind(this.assignTask, this);

      if (!this.client) {
        throw new Error("client parameter is required");
      }
    }

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/assignTask/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop/admin
    */


    Runtime.prototype.assignTask = function(taskUUID, actorId, actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/assignTask/" + taskUUID + "/" + actorId, actAsUser, {}, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/startTask/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop/false
    */


    Runtime.prototype.startTask = function(taskUUID, assign, actAsUser, opts, cb) {
      if (assign == null) {
        assign = false;
      }
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/startTask/" + taskUUID + "/" + assign, actAsUser, {}, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/startActivity/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop
    */


    Runtime.prototype.startActivity = function(activityUUID, actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/startActivity/" + activityUUID, actAsUser, {}, opts, cb);
    };

    return Runtime;

  })();

}).call(this);
