// Generated by CoffeeScript 1.4.0

/*
Handles the identity API in bonita
*/


(function() {
  var Runtime,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Runtime = (function() {

    function Runtime(client) {
      this.client = client;
      this.setProcessInstanceVariable = __bind(this.setProcessInstanceVariable, this);

      this.setVariable = __bind(this.setVariable, this);

      this.instantiateProcess = __bind(this.instantiateProcess, this);

      this.unassignTask = __bind(this.unassignTask, this);

      this.resumeTask = __bind(this.resumeTask, this);

      this.suspendTask = __bind(this.suspendTask, this);

      this.skipTask = __bind(this.skipTask, this);

      this.finishTask = __bind(this.finishTask, this);

      this.startActivity = __bind(this.startActivity, this);

      this.executeTask = __bind(this.executeTask, this);

      this.startTask = __bind(this.startTask, this);

      this.assignTask = __bind(this.assignTask, this);

      if (!this.client) {
        throw new Error("client parameter is required");
      }
    }

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/assignTask/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop/admin
    */


    Runtime.prototype.assignTask = function(taskUUID, actorId, actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/assignTask/" + taskUUID + "/" + actorId, actAsUser, {}, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/startTask/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop/false
    */


    Runtime.prototype.startTask = function(taskUUID, assign, actAsUser, opts, cb) {
      if (assign == null) {
        assign = false;
      }
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/startTask/" + taskUUID + "/" + assign, actAsUser, {}, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:james' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/executeTask/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop/true
    */


    Runtime.prototype.executeTask = function(taskUUID, assign, actAsUser, opts, cb) {
      var data;
      if (assign == null) {
        assign = false;
      }
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      data = {};
      return this.client.post("/API/runtimeAPI/executeTask/" + taskUUID + "/" + assign, actAsUser, data, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/startActivity/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop
    */


    Runtime.prototype.startActivity = function(activityUUID, actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/startActivity/" + activityUUID, actAsUser, {}, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/finishTask/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop/false
    */


    Runtime.prototype.finishTask = function(taskUUID, assign, actAsUser, opts, cb) {
      var data;
      if (assign == null) {
        assign = false;
      }
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      data = {};
      return this.client.post("/API/runtimeAPI/finishTask/" + taskUUID + "/" + assign, actAsUser, data, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/skipTask/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop
    */


    Runtime.prototype.skipTask = function(taskUUID, actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/skipTask/" + taskUUID, actAsUser, {}, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/suspendTask/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop/false
    */


    Runtime.prototype.suspendTask = function(taskUUID, assign, actAsUser, opts, cb) {
      if (assign == null) {
        assign = false;
      }
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/suspendTask/" + taskUUID + "/" + assign, actAsUser, {}, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/resumeTask/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop/false
    */


    Runtime.prototype.resumeTask = function(taskUUID, assign, actAsUser, opts, cb) {
      if (assign == null) {
        assign = false;
      }
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/resumeTask/" + taskUUID + "/" + assign, actAsUser, {}, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:admin' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/unassignTask/QA_Data_Entry--1.2--16--Assign_enter_floor_data--it9f228c2a-3a3e-4889-9dca-28fc00fa1db2--mainActivityInstance--noLoop
    */


    Runtime.prototype.unassignTask = function(taskUUID, actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/unassignTask/" + taskUUID, actAsUser, {}, opts, cb);
    };

    /*
      curl -X POST -d 'options=user:jack' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/xml' -H 'Authorization: Basic cmVzdHVzZXI6cmVzdGJwbQ=='  http://ec2-54-251-77-171.ap-southeast-1.compute.amazonaws.com:8080/bonita-server-rest/API/runtimeAPI/instantiateProcess/QA_Data_Entry--1.51
      result
          <ProcessInstanceUUID>
            <value>QA_Data_Entry--1.51--8</value>
          </ProcessInstanceUUID>
    */


    Runtime.prototype.instantiateProcess = function(processUUID, actAsUser, opts, cb) {
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.client.post("/API/runtimeAPI/instantiateProcess/" + processUUID, actAsUser, {}, opts, cb);
    };

    /*
    */


    Runtime.prototype.setVariable = function(activityUUID, variableId, variableValue, actAsUser, opts, cb) {
      var data;
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      data = {};
      data[variableId] = variableValue;
      return this.client.post("/API/runtimeAPI/setVariable/" + activityUUID, actAsUser, data, opts, cb);
    };

    /*
    */


    Runtime.prototype.setProcessInstanceVariable = function(processInstanceUUID, variableId, variableValue, actAsUser, opts, cb) {
      var data;
      if (opts == null) {
        opts = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      data = {};
      data[variableId] = variableValue;
      return this.client.post("/API/runtimeAPI/setProcessInstanceVariable/" + processInstanceUUID, actAsUser, data, opts, cb);
    };

    return Runtime;

  })();

}).call(this);
