// Generated by CoffeeScript 1.4.0

/*
Storage functionality for modeista-api
*/


(function() {
  var StateMachine;

  StateMachine = require('./state-machine');

  module.exports = {
    StateMachine: StateMachine,
    stateMachine: function(settings) {
      if (settings == null) {
        settings = {};
      }
      return new StateMachine(settings);
    }
  };

}).call(this);
