// Generated by CoffeeScript 1.4.0
(function() {
  var State, _;

  _ = require('underscore');

  module.exports = State = (function() {

    function State(data) {
      if (data == null) {
        data = {};
      }
      _.extend(this, data);
      console.log("STATE");
      console.log(JSON.stringify(this));
    }

    return State;

  })();

}).call(this);
