// Generated by CoffeeScript 1.4.0
(function() {
  var ProcessDefinitionSchema, ProcessDefinitionsMethods, Store, mongoose, _;

  mongoose = require('mongoose');

  _ = require('underscore');

  ProcessDefinitionSchema = require('./schemas/process-definition-schema');

  ProcessDefinitionsMethods = require('./methods/process-definition-methods');

  module.exports = Store = (function() {

    function Store(settings) {
      this.settings = settings != null ? settings : {};
      _.defaults(this.settings, {});
      this.models = {
        ProcessDefinition: mongoose.model("ProcessDefinition", ProcessDefinitionSchema)
      };
      this.processDefinitions = new ProcessDefinitionsMethods(this.models);
    }

    return Store;

  })();

}).call(this);
