// Generated by CoffeeScript 1.4.0
(function() {
  var ProcessDefinitionSchema, ProcessDefinitionsMethods, Store, TaskMethods, TaskSchema, mongoose, _;

  mongoose = require('mongoose');

  _ = require('underscore');

  ProcessDefinitionSchema = require('./schemas/process-definition-schema');

  TaskSchema = require('./schemas/task-schema');

  ProcessDefinitionsMethods = require('./methods/process-definition-methods');

  TaskMethods = require('./methods/task-methods');

  module.exports = Store = (function() {

    function Store(settings) {
      this.settings = settings != null ? settings : {};
      _.defaults(this.settings, {});
      this.models = {
        Task: mongoose.model("Task", TaskSchema),
        ProcessDefinition: mongoose.model("ProcessDefinition", ProcessDefinitionSchema)
      };
      this.processDefinitions = new ProcessDefinitionsMethods(this.models);
      this.tasks = new TaskMethods(this.models);
    }

    return Store;

  })();

}).call(this);
