// Generated by CoffeeScript 1.4.0
(function() {
  var BoardMethods, BoardSchema, ProcessDefinitionSchema, ProcessDefinitionsMethods, RoleMethods, RoleSchema, Store, TaskMethods, TaskSchema, mongoose, _;

  mongoose = require('mongoose');

  _ = require('underscore');

  ProcessDefinitionSchema = require('./schemas/process-definition-schema');

  TaskSchema = require('./schemas/task-schema');

  RoleSchema = require('./schemas/role-schema');

  BoardSchema = require('./schemas/board-schema');

  ProcessDefinitionsMethods = require('./methods/process-definition-methods');

  TaskMethods = require('./methods/task-methods');

  RoleMethods = require('./methods/role-methods');

  BoardMethods = require('./methods/board-methods');

  module.exports = Store = (function() {

    function Store(settings) {
      this.settings = settings != null ? settings : {};
      _.defaults(this.settings, {});
      this.models = {
        Role: mongoose.model("Role", RoleSchema),
        Task: mongoose.model("Task", TaskSchema),
        ProcessDefinition: mongoose.model("ProcessDefinition", ProcessDefinitionSchema),
        Board: mongoose.model("Board", BoardSchema)
      };
      this.processDefinitions = new ProcessDefinitionsMethods(this.models);
      this.tasks = new TaskMethods(this.models);
      this.roles = new RoleMethods(this.models);
      this.boards = new BoardMethods(this.models);
    }

    return Store;

  })();

}).call(this);
