// Generated by CoffeeScript 1.4.0
(function() {
  var toBoardTransformer, toNextActionTransformer, _;

  _ = require('underscore');

  require('pkginfo')(module, 'version');

  toBoardTransformer = require('./to-board-transformer');

  toNextActionTransformer = require('./to-next-action-transformer');

  module.exports = {
    toBoard: toBoardTransformer,
    toNextAction: toNextActionTransformer
  };

}).call(this);
