// Generated by CoffeeScript 1.4.0
(function() {
  var toBoardTransformer, _;

  _ = require('underscore');

  require('pkginfo')(module, 'version');

  toBoardTransformer = require('./to-board-transformer');

  module.exports = {
    toBoard: toBoardTransformer
  };

}).call(this);
