// Generated by CoffeeScript 1.4.0

/*
# Top level file for modeista.com
*/


(function() {
  var app, port;

  app = module.exports = new (require('./app'))();

  port = process.env.PORT || 8001;

  app.start(require.main === module ? port : null);

}).call(this);
