// Generated by CoffeeScript 1.4.0
(function() {
  var RoutesAppPathHelper, RoutesOther, protectResource, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  RoutesAppPathHelper = require('./routes-app-path-helper');

  protectResource = require('../site/protect-resource');

  module.exports = RoutesOther = (function() {

    function RoutesOther(settings) {
      this.getAdminProcessDefinitionsEdit = __bind(this.getAdminProcessDefinitionsEdit, this);

      this.getAdminProcessDefinitionsLayout = __bind(this.getAdminProcessDefinitionsLayout, this);

      this.getAdminProcessDefinitionsForm = __bind(this.getAdminProcessDefinitionsForm, this);

      this.getAdminProcessDefinitionsAdd = __bind(this.getAdminProcessDefinitionsAdd, this);

      this.getAdminProcessDefinitions = __bind(this.getAdminProcessDefinitions, this);

      this.getAdminRolesAdd = __bind(this.getAdminRolesAdd, this);

      this.getAdminRoles = __bind(this.getAdminRoles, this);

      this.getAdminUsersAdd = __bind(this.getAdminUsersAdd, this);

      this.getAdminUsers = __bind(this.getAdminUsers, this);

      this.getAdminTasks = __bind(this.getAdminTasks, this);

      this.getTask = __bind(this.getTask, this);

      this.getMain = __bind(this.getMain, this);

      this.getApp = __bind(this.getApp, this);

      this.getChangePassword = __bind(this.getChangePassword, this);

      this.getHelpTerms = __bind(this.getHelpTerms, this);

      this.getHelpSetup = __bind(this.getHelpSetup, this);

      this.getHelp = __bind(this.getHelp, this);

      this.setupRoutes = __bind(this.setupRoutes, this);

      this.setupLocals = __bind(this.setupLocals, this);
      _.extend(this, settings);
      if (!this.app) {
        throw new Error("app parameter is required");
      }
    }

    RoutesOther.prototype.setupLocals = function() {
      return this.app.locals.routesApps = this.routesAppPathHelper = new RoutesAppPathHelper;
    };

    RoutesOther.prototype.setupRoutes = function() {
      this.app.get('/app', protectResource(), this.getApp);
      this.app.get('/app/main', this.getMain);
      this.app.get('/app/task', this.getTask);
      this.app.get('/app/admin/users', this.getAdminUsers);
      this.app.get('/app/admin/change-password', this.getChangePassword);
      this.app.get('/app/admin/users/add', this.getAdminUsersAdd);
      this.app.get('/app/admin/roles', this.getAdminRoles);
      this.app.get('/app/admin/roles/add', this.getAdminRolesAdd);
      this.app.get('/app/admin/process-definitions', this.getAdminProcessDefinitions);
      this.app.get('/app/admin/process-definitions/add', this.getAdminProcessDefinitionsAdd);
      this.app.get('/app/admin/process-definitions/form', this.getAdminProcessDefinitionsForm);
      this.app.get('/app/admin/process-definitions/layout', this.getAdminProcessDefinitionsLayout);
      this.app.get('/app/admin/process-definitions/edit', this.getAdminProcessDefinitionsEdit);
      this.app.get('/app/admin/tasks', this.getAdminTasks);
      this.app.get('/app/help', this.getHelp);
      this.app.get('/app/help/terms', this.getHelpTerms);
      return this.app.get('/app/help/setup', this.getHelpSetup);
    };

    RoutesOther.prototype.getHelp = function(req, res, next) {
      return res.render('app/help/index', {
        pretty: true
      });
    };

    RoutesOther.prototype.getHelpSetup = function(req, res, next) {
      return res.render('app/help/setup', {
        pretty: true
      });
    };

    RoutesOther.prototype.getHelpTerms = function(req, res, next) {
      return res.render('app/help/terms', {
        pretty: true
      });
    };

    RoutesOther.prototype.getChangePassword = function(req, res, next) {
      return res.render('app/admin/users-changepassword', {
        pretty: true
      });
    };

    RoutesOther.prototype.getApp = function(req, res, next) {
      return res.render('app/index', {
        pretty: true
      });
    };

    RoutesOther.prototype.getMain = function(req, res, next) {
      return res.render('app/main', {
        pretty: true
      });
    };

    RoutesOther.prototype.getTask = function(req, res, next) {
      return res.render('app/task', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminTasks = function(req, res, next) {
      return res.render('app/admin/tasks', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminUsers = function(req, res, next) {
      return res.render('app/admin/users', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminUsersAdd = function(req, res, next) {
      return res.render('app/admin/users-add', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminRoles = function(req, res, next) {
      return res.render('app/admin/roles', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminRolesAdd = function(req, res, next) {
      return res.render('app/admin/roles-add', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminProcessDefinitions = function(req, res, next) {
      return res.render('app/admin/process-definitions', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminProcessDefinitionsAdd = function(req, res, next) {
      return res.render('app/admin/process-definitions-add', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminProcessDefinitionsForm = function(req, res, next) {
      return res.render('app/admin/process-definitions-form', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminProcessDefinitionsLayout = function(req, res, next) {
      return res.render('app/admin/process-definitions-layout', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminProcessDefinitionsEdit = function(req, res, next) {
      return res.render('app/admin/process-definition-edit', {
        pretty: true
      });
    };

    return RoutesOther;

  })();

}).call(this);
