// Generated by CoffeeScript 1.4.0
(function() {
  var RoutesLegacy, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  module.exports = RoutesLegacy = (function() {

    function RoutesLegacy(settings) {
      this.setupRoutes = __bind(this.setupRoutes, this);

      this.setupLocals = __bind(this.setupLocals, this);
      _.extend(this, settings);
      if (!this.app) {
        throw new Error("app parameter is required");
      }
      if (!this.backend) {
        throw new Error("backend parameter is required");
      }
    }

    RoutesLegacy.prototype.setupLocals = function() {};

    RoutesLegacy.prototype.setupRoutes = function() {
      this.app.get('/tasks/:idx?', this.backend.tasks);
      this.app.get('/quotes', this.backend.quotes);
      this.app.post('/users', this.backend.create_user);
      this.app.post('/login', this.backend.login);
      this.app.post('/logout', this.backend.logout);
      this.app.get('/current_user', this.backend.current_user);
      this.app.post('/faxes', this.backend.create_fax);
      this.app.get('/board', this.backend.board);
      this.app.get('/bods/:bodid', this.backend.show_bod);
      return this.app.get('/ourselves', this.backend.ourselves);
    };

    return RoutesLegacy;

  })();

}).call(this);
