// Generated by CoffeeScript 1.4.0
(function() {
  var RoutesAppPathHelper, RoutesOther, protectResource, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  RoutesAppPathHelper = require('./routes-app-path-helper');

  protectResource = require('../site/protect-resource');

  module.exports = RoutesOther = (function() {

    function RoutesOther(settings) {
      this.getAdminUsersAdd = __bind(this.getAdminUsersAdd, this);

      this.getAdminUsers = __bind(this.getAdminUsers, this);

      this.getTask = __bind(this.getTask, this);

      this.getMain = __bind(this.getMain, this);

      this.getApp = __bind(this.getApp, this);

      this.setupRoutes = __bind(this.setupRoutes, this);

      this.setupLocals = __bind(this.setupLocals, this);
      _.extend(this, settings);
      if (!this.app) {
        throw new Error("app parameter is required");
      }
    }

    RoutesOther.prototype.setupLocals = function() {
      return this.app.locals.routesApps = this.routesAppPathHelper = new RoutesAppPathHelper;
    };

    RoutesOther.prototype.setupRoutes = function() {
      this.app.get('/app', protectResource(), this.getApp);
      this.app.get('/app/main', this.getMain);
      this.app.get('/app/task', this.getTask);
      this.app.get('/app/admin/users', this.getAdminUsers);
      return this.app.get('/app/admin/users/add', this.getAdminUsersAdd);
    };

    RoutesOther.prototype.getApp = function(req, res, next) {
      return res.render('app/index', {
        pretty: true
      });
    };

    RoutesOther.prototype.getMain = function(req, res, next) {
      return res.render('app/main', {
        pretty: true
      });
    };

    RoutesOther.prototype.getTask = function(req, res, next) {
      return res.render('app/task', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminUsers = function(req, res, next) {
      return res.render('app/admin/users', {
        pretty: true
      });
    };

    RoutesOther.prototype.getAdminUsersAdd = function(req, res, next) {
      return res.render('app/admin/users-add', {
        pretty: true
      });
    };

    return RoutesOther;

  })();

}).call(this);
