// Generated by CoffeeScript 1.4.0
(function() {
  var RoutesLegacy, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  module.exports = RoutesLegacy = (function() {

    function RoutesLegacy(settings) {
      this.setupRoutes = __bind(this.setupRoutes, this);

      this.setupLocals = __bind(this.setupLocals, this);
      _.extend(this, settings);
      if (!this.app) {
        throw new Error("app parameter is required");
      }
    }

    RoutesLegacy.prototype.setupLocals = function() {};

    RoutesLegacy.prototype.setupRoutes = function() {
      /*
          @app.post '/sales', andLoggedIn, backend.create_task
          @app.get '/tasks/:idx?', backend.tasks
          @app.get '/quotes', backend.quotes
          @app.post '/users', backend.create_user
          @app.post '/login', app.session_mw, backend.login
          @app.post '/logout', backend.logout
          @app.get '/current_user', backend.current_user
          @app.post '/faxes', backend.create_fax 
          @app.get '/board', backend.board 
          @app.get '/bods/:bodid', backend.show_bod 
          @app.get '/ourselves', backend.ourselves
      */

    };

    return RoutesLegacy;

  })();

}).call(this);
