// Generated by CoffeeScript 1.4.0
(function() {
  var RoutesSetup, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  module.exports = RoutesSetup = (function() {

    function RoutesSetup(settings) {
      this.setup = __bind(this.setup, this);

      this.setupRoutes = __bind(this.setupRoutes, this);

      this.setupLocals = __bind(this.setupLocals, this);
      _.extend(this, settings);
      if (!this.app) {
        throw new Error("app parameter is required");
      }
      if (!this.passport) {
        throw new Error("passport parameter is required");
      }
      if (!this.identityStore) {
        throw new Error("identityStore parameter is required");
      }
    }

    RoutesSetup.prototype.setupLocals = function() {};

    RoutesSetup.prototype.setupRoutes = function() {
      return this.app.post('/setup', this.setup);
    };

    /*
      curl -X POST http://localhost:8001/setup
    */


    RoutesSetup.prototype.setup = function(req, res, next) {
      var data,
        _this = this;
      data = {
        roles: ['admin'],
        username: 'admin',
        password: 'bpm',
        primaryEmail: 'bpm@admin.com'
      };
      return this.identityStore.users.create(data, function(err, user) {
        if (err) {
          return next(err);
        }
        return res.json({
          message: "success"
        });
      });
    };

    return RoutesSetup;

  })();

}).call(this);
