// Generated by CoffeeScript 1.4.0
(function() {
  var RoutesOther, RoutesRootPathHelper, protectResource, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  RoutesRootPathHelper = require('./routes-root-path-helper');

  protectResource = require('../site/protect-resource');

  module.exports = RoutesOther = (function() {

    function RoutesOther(settings) {
      this.status = __bind(this.status, this);

      this.home = __bind(this.home, this);

      this.setupRoutes = __bind(this.setupRoutes, this);

      this.setupLocals = __bind(this.setupLocals, this);
      _.extend(this, settings);
      if (!this.app) {
        throw new Error("app parameter is required");
      }
    }

    RoutesOther.prototype.setupLocals = function() {
      return this.app.locals.routesRoot = this.routesRootPathHelper = new RoutesRootPathHelper;
    };

    RoutesOther.prototype.setupRoutes = function() {
      this.app.get('/', this.home);
      return this.app.get('/status', this.status);
    };

    RoutesOther.prototype.home = function(req, res, next) {
      return res.redirect("/app");
    };

    RoutesOther.prototype.status = function(req, res, next) {
      return res.json({
        running: true,
        uptime: process.uptime(),
        memoryUsage: process.memoryUsage(),
        versions: process.versions,
        pid: process.pid
      });
    };

    return RoutesOther;

  })();

}).call(this);
