// Generated by CoffeeScript 1.4.0
(function() {
  var RoutesOther, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  module.exports = RoutesOther = (function() {

    function RoutesOther(settings) {
      this.status = __bind(this.status, this);

      this.home = __bind(this.home, this);
      _.extend(this, settings);
      if (!this.app) {
        throw new Error("app parameter is required");
      }
      this.app.get('/', this.home);
      this.app.get('/status', this.status);
    }

    RoutesOther.prototype.home = function(req, res, next) {
      return res.redirect("/app");
    };

    RoutesOther.prototype.status = function(req, res, next) {
      return res.json({
        running: true,
        uptime: process.uptime(),
        memoryUsage: process.memoryUsage(),
        versions: process.versions,
        pid: process.pid
      });
    };

    return RoutesOther;

  })();

}).call(this);
