// Generated by CoffeeScript 1.4.0

/*
Convert an xlsx to a form for display
*/


(function() {
  var LayoutForm, XlsxForm, formAndHtml,
    _this = this;

  XlsxForm = require('./xlsx-form');

  LayoutForm = require('./layout-form');

  formAndHtml = require('./form-and-html');

  module.exports = {
    loadAndConvert: function(path, cb) {
      var form,
        _this = this;
      form = new XlsxForm();
      return form.loadFromPath(path, function(err) {
        var html;
        form = {};
        html = formAndHtml.createHtml(form);
        return cb(null, html);
      });
    },
    loadAndConvertVba: function(pathToJson, cb) {
      var lf;
      lf = new LayoutForm();
      return lf.loadVbaOutputFromPath(pathToJson, function(err, converted) {
        return cb(err, converted);
      });
    }
  };

}).call(this);
